### ISSUE TITLE
release 1.1

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-reactor#31]
I think we are ready for a maintanence release.

New features: processEnginePlugin events, smaller fixes and examples.

**Comment by saig0** [comment]
@jangalinski, we have a failing test case. The problem occurs when the test MultiInstanceTaskTest is executed before ReactorProcessEnginePluginTest. Can you please check this?

**Comment by jangalinski** [comment]
First check locally: IDE and maven run through. Will try to force random order of tests and see what happens.

**Comment by saig0** [comment]
@jangalinski , please try to run it with maven in reversealphabetical order.

Log from CI:
```
Fehlermeldung

Expecting actual Task {id='34', processInstanceId='4', taskDefinitionKey='task_b', name='Do "B"'} to be assigned to user 'foo', but found it to be assigned to 'null'!
Stacktrace

java.lang.AssertionError: Expecting actual Task {id='34', processInstanceId='4', taskDefinitionKey='task_b', name='Do "B"'} to be assigned to user 'foo', but found it to be assigned to 'null'!
	at org.camunda.bpm.engine.test.assertions.TaskAssert.isAssignedTo(TaskAssert.java:58)
	at org.camunda.bpm.extension.reactor.plugin.ReactorProcessEnginePluginTest.fire_events_on_userTasks(ReactorProcessEnginePluginTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Standard Ausgabe (STDOUT)

Event{id=3623fe30-1534-11e6-6a09-e3a5c77ad9d0, headers={context=task, element=task_a, event=complete, process=process_a, type={type}}, replyTo=null, key=/camunda/task/{type}/process_a/task_a/complete, data=Task[7]}
Event{id=362a3fc0-1534-11e6-6a09-e3a5c77ad9d0, headers={context=bpmn, element=task_a, event=end, process=process_a, type=userTask}, replyTo=null, key=/camunda/bpmn/userTask/process_a/task_a/end, data=ProcessInstance[4]}
Event{id=362a66d0-1534-11e6-6a09-e3a5c77ad9d0, headers={context=bpmn, element=SequenceFlow_2, event=take, process=process_a, type=sequenceFlow}, replyTo=null, key=/camunda/bpmn/sequenceFlow/process_a/SequenceFlow_2/take, data=ProcessInstance[4]}
Event{id=362a8de0-1534-11e6-6a09-e3a5c77ad9d0, headers={context=bpmn, element=task_b, event=start, process=process_a, type=userTask}, replyTo=null, key=/camunda/bpmn/userTask/process_a/task_b/start, data=ProcessInstance[4]}
Event{id=362adc00-1534-11e6-6a09-e3a5c77ad9d0, headers={context=task, element=task_b, event=create, process=process_a, type={type}}, replyTo=null, key=/camunda/task/{type}/process_a/task_b/create, data=Task[34]}
Standard Fehler (STDERR)

[main] [INFO] cfg - ENGINE-12003 Plugin 'ReactorProcessEnginePlugin' activated on process engine 'default'
[main] [INFO] engine - ENGINE-00001 Process Engine default created.
[main] [DEBUG] CamundaEventBus - registered  to '/camunda/{context}/{type}/process_a/{element}/{event}'
[main] [DEBUG] CamundaEventBus - registered  to '/camunda/{context}/{type}/process_a/task_a/{event}'
[main] [DEBUG] CamundaEventBus - registered  to '/camunda/{context}/{type}/process_a/task_a/complete'
[main] [DEBUG] CamundaEventBus - registered  to '/camunda/{context}/{type}/process_a/task_a/start'
[main] [DEBUG] CamundaEventBus - registered  to '/camunda/{context}/{type}/process_a/task_a/end'
[main] [DEBUG] CamundaEventBus - registered  to '/camunda/{context}/{type}/{process}/{element}/create'
[main] [DEBUG] CamundaEventBus - registered  to '/camunda/{context}/{type}/{process}/{element}/{event}'
[main] [DEBUG] CamundaEventBus - registered  to '/camunda/task/{type}/{process}/{element}/create'
[main] [DEBUG] CamundaEventBus - Notify execution: ProcessInstance[4] on topic /camunda/bpmn/startEvent/process_a/StartEvent_1/start
[main] [DEBUG] CamundaEventBus - Notify execution: ProcessInstance[4] on topic /camunda/bpmn/startEvent/process_a/StartEvent_1/end
[main] [DEBUG] CamundaEventBus - Notify execution: ProcessInstance[4] on topic /camunda/bpmn/sequenceFlow/process_a/SequenceFlow_1/take
[main] [DEBUG] CamundaEventBus - Notify execution: ProcessInstance[4] on topic /camunda/bpmn/userTask/process_a/task_a/start
[main] [DEBUG] CamundaEventBus - Notify execution: Task[7] on topic /camunda/task/{type}/process_a/task_a/create
[main] [DEBUG] CamundaEventBus - Notify execution: Task[7] on topic /camunda/task/{type}/process_a/task_a/assignment
[main] [DEBUG] CamundaEventBus - Notify execution: Task[7] on topic /camunda/task/{type}/process_a/task_a/complete
[main] [DEBUG] CamundaEventBus - Notify execution: ProcessInstance[4] on topic /camunda/bpmn/userTask/process_a/task_a/end
[main] [DEBUG] CamundaEventBus - Notify execution: ProcessInstance[4] on topic /camunda/bpmn/sequenceFlow/process_a/SequenceFlow_2/take
[main] [DEBUG] CamundaEventBus - Notify execution: ProcessInstance[4] on topic /camunda/bpmn/userTask/process_a/task_b/start
[main] [DEBUG] CamundaEventBus - Notify execution: Task[34] on topic /camunda/task/{type}/process_a/task_b/create
[main] [DEBUG] CamundaEventBus - Notify execution: Task[34] on topic /camunda/task/{type}/process_a/task_b/delete
[main] [DEBUG] CamundaEventBus - Notify execution: ProcessInstance[4] on topic /camunda/bpmn/userTask/process_a/task_b/end
```

**Comment by jangalinski** [comment]
Got it, will fix in #33

**Comment by jangalinski** [comment]
I just used a mock test now (unit) instead of an itest (process actually started). Effect is the same. So please try again

**Comment by jangalinski** [comment]
ah and btw:

release version: 1.1
next dev version: 1.2-SNAPSHOT

**Comment by saig0** [comment]
Done.

**Comment by jangalinski** [comment]
still not on central: https://repo1.maven.org/maven2/org/camunda/bpm/extension/camunda-bpm-reactor-core/
could you please check the sonatype job?

**Comment by saig0** [comment]
Now, it is on maven central.

**Comment by jangalinski** [comment]
Thanks, perfect
